'''

************* DISCLAIMER: THESE TASKS WERE POSTED ON https://www.practicepython.org ***********************************
************************* I AM ONLY PROVIDING SOLUTIONS ***************************************************************



************ PLEASE READ THE TASK DESCRIPTION CAREFULLY, I'VE MADE CHANGES (CORRECTIONS) TO IT ************************
Project/Exercise 18 : Cows and Bulls (https://www.practicepython.org/)
                     Create a program that will play the “cows and bulls” game with the user. The game works like this:
                     Randomly generate a 4-digit number (no repetition in digits). Ask the user to guess a 4-digit number.
                     For every digit that the user guessed correctly in the correct place, they have a “bull”. For every
                     digit the user guessed correctly in the wrong place is a “cow”.
                     Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user
                     guesses the correct number, the game is over. Keep track of the number of guesses the user makes
                     throughout the game and tell the user at the end.

                     Say the number generated by the computer is 1038. An example interaction could look like this:

                     Welcome to the Cows and Bulls Game!
                     Enter a number:
                     #>>> 1234
                     0 cows, 2 bulls
                     #>>> 1256
                     0 cow, 1 bull
                     ...... Until the user guesses the number.

Solution
Created on: 17/08/2019
Created by: Nivedita Pagar
'''


import random

game_end = 0
trial = 0


def random_four_digit():
    '''generates a random four digit number

        Parameters
        -----------
        None

        Returns
        -----------
        None
        '''
    global random_number

    # create an empty string every time you play a new game
    # an alternate approach would be to use lists
    random_number = ""
    count = 0

    # make sure you generate exactly a four digit number
    while count < 4:
        # generate a random digit
        random_temp = str(random.randint(0,9))

        # if the random digit is not already in the string, add it to the string
        if random_temp not in random_number:
            random_number += random_temp
            # increment this only when you add a new digit to the string
            count += 1
    print(random_number)
    return random_number


'''Function to store and evaluate the user's guess'''


def user_guess():
    '''asks for user's guess and evaluates it

            Parameters
            -----------
            None

            Returns
            -----------
            None
            '''
    global user_number, valid
    valid = 0
    while not valid:

        # create an empty string every time the user takes a new guess
        user_number = ""
        user_temp = input("Guess the four digit number: ")
        try:
            # try to type cast the user input to an integer to make sure there are no characters
            # if there is an exception, it means that there are some unwanted characters
            user_int = int(user_temp)

            # make sure the user inputs exactly four digits
            if len(user_temp) == 4:
                for i in range(len(user_temp)):

                    # make sure there are no duplicates
                    if user_temp[i] not in user_number:
                        user_number += user_temp[i]

                # if there are duplicates, the length will not be 4
                if len(user_number) != 4:
                    print("No repetitions !!")
                else:
                    print(user_number)

                    # variable to ensure that the input is valid
                    valid = 1
            else:
                # if the number is longer than four digits, inform the user
                print("Please enter a four digit number")
        except:
            # if there are any other characters, inform the user
            print("Only integers allowed")


'''Function to play the cow and bull game'''


def cow_bull_game():
    '''plays the cow_bull game with the randomly generated number and user's guess

                Parameters
                -----------
                None

                Returns
                -----------
                None
                '''
    global winner, trial
    trial += 1

    #  if the user input is valid, play the game
    if valid == 1:
        cow = 0
        bull = 0
        winner = 0

        # iterate through the two strings to find common digits
        for i in range(len(random_number)):
            for j in range(len(user_number)):

                # when you find a common digit between the two strings
                if random_number[i] == user_number[j]:

                    # if the index of the duplicates is the same, its a bull
                    if i == j:
                        bull += 1

                        # if not, then its a cow
                    else:
                        cow += 1

        # after all the iterations, if there are 4 bulls, it means that the user has won
        if bull == 4:
            print("Bang on !! Congratulations, you won !!\nYou took " + str(trial) + " trials")
            winner = 1

        # if bull != 4, then print the number of cows and bulls to help the user
        else:
            print("Your guess has " + str(bull) + " bulls and " + str(cow) + " cows")
    return winner


def main():
    '''main function to call all the other functions to play the game

                   Parameters
                   -----------
                   None

                   Returns
                   -----------
                   None
                   '''
    cont = 1

    # loop runs as long as user wants to continue playing
    while cont == 1:
        random_four_digit()

        # loop runs until the user guesses the correct number
        while game_end == 0:
            user_guess()
            cow_bull_game()

            # if the user wins, break out of the loop and ask if they want to play again
            if winner == 1:
                break
        cont = int(input("Do you want to continue playing ?\nEnter 1 for yes and 0 for no: "))

    # parting statement if the user doesn't want to continue
    print("Have a good day !!")


# Call to the main function
main()
